# Generated by Django 5.2.7 on 2025-10-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=80)),
                ('model_year', models.PositiveIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance')], default='available', max_length=12)),
                ('plate_no', models.CharField(max_length=20, unique=True)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('transmission', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=6)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
